/// A detected cross-domain life pattern.
///
/// PatternInsights are generated by the [PatternEngineService] and represent
/// correlations between different life signals (sleep, mood, energy, activity,
/// drinks, notes, finance). They use supportive language — never medical claims.
class PatternInsight {
  final String id;
  final String titleEn;
  final String titleHu;
  final String descriptionEn;
  final String descriptionHu;

  /// 0.0 – 1.0: how strongly the data supports this pattern.
  final double confidence;

  /// Which life domains are involved (e.g. ['sleep', 'energy']).
  final List<String> relatedSignals;

  final PatternDomain domain;
  final PatternSeverity severity;

  /// ISO-8601 date string of the analysis window end.
  final String analysisDate;

  /// Number of data-points that contributed to this insight.
  final int dataPoints;

  const PatternInsight({
    required this.id,
    required this.titleEn,
    required this.titleHu,
    required this.descriptionEn,
    required this.descriptionHu,
    required this.confidence,
    required this.relatedSignals,
    required this.domain,
    this.severity = PatternSeverity.info,
    required this.analysisDate,
    required this.dataPoints,
  });

  String title(String locale) => locale == 'hu' ? titleHu : titleEn;
  String description(String locale) => locale == 'hu' ? descriptionHu : descriptionEn;

  Map<String, dynamic> toMap() => {
        'id': id,
        'titleEn': titleEn,
        'titleHu': titleHu,
        'descriptionEn': descriptionEn,
        'descriptionHu': descriptionHu,
        'confidence': confidence,
        'relatedSignals': relatedSignals.join(','),
        'domain': domain.name,
        'severity': severity.name,
        'analysisDate': analysisDate,
        'dataPoints': dataPoints,
      };

  factory PatternInsight.fromMap(Map<String, dynamic> map) => PatternInsight(
        id: map['id'] as String,
        titleEn: map['titleEn'] as String,
        titleHu: map['titleHu'] as String,
        descriptionEn: map['descriptionEn'] as String,
        descriptionHu: map['descriptionHu'] as String,
        confidence: (map['confidence'] as num).toDouble(),
        relatedSignals:
            (map['relatedSignals'] as String).split(',').where((s) => s.isNotEmpty).toList(),
        domain: PatternDomain.values.firstWhere(
          (d) => d.name == map['domain'],
          orElse: () => PatternDomain.general,
        ),
        severity: PatternSeverity.values.firstWhere(
          (s) => s.name == map['severity'],
          orElse: () => PatternSeverity.info,
        ),
        analysisDate: map['analysisDate'] as String,
        dataPoints: map['dataPoints'] as int,
      );
}

enum PatternDomain {
  sleep,
  mood,
  energy,
  activity,
  hydration,
  notes,
  finance,
  general,
}

enum PatternSeverity {
  info,
  gentle,
  notable,
}
